// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(object) {
    var sprite;
    sprite = new PIXI.Sprite(object.texture);
    sprite.anchor.x = .5;
    sprite.anchor.y = .5;
    sprite.position.x = object.position.x;
    sprite.position.y = object.position.y;
    sprite.rotation = object.rotation;
    sprite.width *= object.width;
    sprite.height *= object.height;
    if (object.rotation) {
      return sprite;
    } else {
      return void 0;
    }
  };

}).call(this);
