// Generated by CoffeeScript 1.6.1
(function() {
  var new_weapon, texture;

  new_weapon = require('../weapon.js');

  texture = "/img/short-bullet.png";

  module.exports = new_weapon({
    range: 400,
    rate: 5,
    projectile: {
      texture: texture,
      speed: 60,
      acceleration: 0,
      damage: 7.5,
      width: .5,
      height: .5
    }
  });

}).call(this);
