// Generated by CoffeeScript 1.6.1
(function() {
  var render, small_ship, texture, update;

  texture = PIXI.Texture.fromImage("ship.png");

  render = function() {
    var sprite;
    sprite = new PIXI.Sprite(texture);
    sprite.anchor.x = .5;
    sprite.anchor.y = .5;
    sprite.position.x = this.xpos;
    sprite.position.y = this.ypos;
    return sprite;
  };

  update = function(dt) {
    var copy;
    this.xvel = this.xvel + this.xacel;
    this.yvel = this.yvel + this.yacel;
    this.xpos = this.xpos + this.xvel;
    this.ypos = this.ypos + this.yvel;
    this.xacel = (this.xacel + Math.random() - .5) * dt;
    this.yacel = (this.yacel + Math.random() - .5) * dt;
    this.xacel = this.xacel + (Math.pow(200 - this.xpos, 3) * 0.00000001);
    this.yacel = this.yacel + (Math.pow(150 - this.ypos, 3) * 0.00000001);
    copy = function(x) {
      return JSON.parse(JSON.stringify(x));
    };
    return [this];
  };

  small_ship = function() {
    return {
      type: 'ship',
      xpos: 200,
      ypos: 150,
      xvel: 0,
      yvel: 0,
      xacel: 0,
      yacel: 0,
      render: render,
      update: update
    };
  };

  module.exports = small_ship;

}).call(this);
