// Generated by CoffeeScript 1.6.1
(function() {
  var MAX_PLAYERS, OPEN_GAMES, app, createPlayer, express, gameServer, io, lobby, player_id, port, prettify_games, server, start_game, url;

  MAX_PLAYERS = 2;

  OPEN_GAMES = 9;

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  port = 8080;

  io.set('log level', 1);

  lobby = require('./lib/lobby');

  gameServer = require('./server/main.js');

  url = process.env.SUBDOMAIN != null ? "http://" + process.env.SUBDOMAIN + ".nodejitsu.com" : "http://localhost:" + port;

  server.listen(port);

  console.log("Express server listening on port " + port);

  console.log("At url:");

  console.log(url);

  app.get('/', function(req, res) {
    console.log('game started');
    return res.sendfile("" + __dirname + "/client/build/index.html");
  });

  app.get('/index.js', function(req, res) {
    return res.sendfile("" + __dirname + "/client/build/index.js");
  });

  app.use("/img", express["static"]("" + __dirname + "/img"));

  start_game = function(players) {
    var gameTag, player, _i, _len;
    gameTag = "game-" + this.id;
    for (_i = 0, _len = players.length; _i < _len; _i++) {
      player = players[_i];
      player.socket.leave('lobby');
      player.socket.join(gameTag);
    }
    io.sockets["in"](gameTag).emit('game_start');
    return gameServer.start(function(state) {
      return io.sockets["in"](gameTag).emit('update', state);
    });
  };

  lobby = lobby.create({
    on_full: start_game
  });

  prettify_games = function(open_games) {
    var game, id, _results;
    console.log('pretty', open_games);
    _results = [];
    for (id in open_games) {
      game = open_games[id];
      _results.push({
        id: id,
        players: game.persons.length
      });
    }
    return _results;
  };

  player_id = 0;

  createPlayer = function(socket) {
    return {
      id: player_id++,
      socket: socket
    };
  };

  io.sockets.on('connection', function(socket) {
    var player;
    player = createPlayer(socket);
    socket.join('lobby');
    console.log("emitting open", prettify_games(lobby.open_groups));
    socket.emit('open_games', prettify_games(lobby.open_groups));
    return socket.on('join', function(id) {
      console.log("emitting open post join", prettify_games(lobby.open_groups));
      lobby.group(id).add(player);
      return io.sockets["in"]('lobby').emit('open_games', prettify_games(lobby.open_groups));
    });
  });

}).call(this);
