// Generated by CoffeeScript 1.6.1
(function() {
  var attach, default_update, hit, new_ship, texture;

  texture = "/img/ship.png";

  hit = function(item) {
    return this.health -= item.damage;
  };

  attach = function(item) {
    this.attachments.concat(item);
    item.attached_to = this;
    item.position.x = this.position.x;
    return item.position.y = this.position.y;
  };

  default_update = function(dt) {
    this.xvel = this.xvel + (this.xacel * dt);
    this.yvel = this.yvel + (this.yacel * dt);
    this.position.x = this.position.x + (this.xvel * dt);
    this.position.y = this.position.y + (this.yvel * dt);
    this.xacel = this.xacel + ((Math.random() - .5) * this.acceleration);
    this.yacel = this.yacel + ((Math.random() - .5) * this.acceleration);
    if (this.xvel > 30) {
      this.xacel = -5;
    } else if (this.xvel < -30) {
      this.xacel = 5;
    }
    if (this.yvel > 30) {
      this.yacel = -5;
    } else if (this.yvel < -30) {
      this.yacel = 5;
    }
    if (this.health > 0) {
      return this;
    } else {
      return [];
    }
  };

  new_ship = function(options) {
    if (options == null) {
      options = {};
    }
    return function(xpos, ypos) {
      return {
        type: "ship",
        update: options.update || default_update,
        health: options.health || 100,
        position: {
          x: xpos || 0,
          y: ypos || 0
        },
        width: options.width,
        height: options.height,
        acceleration: options.acceleration || 0.1,
        xvel: 0,
        yvel: 0,
        xacel: 0,
        yacel: 0,
        texture: options.texture || texture,
        attachments: [],
        attach: attach,
        hit: hit
      };
    };
  };

  module.exports = new_ship;

}).call(this);
