// Generated by CoffeeScript 1.6.1
(function() {
  var default_render, default_update, new_ship, texture;

  texture = PIXI.Texture.fromImage("ship.png");

  default_render = function() {
    var sprite;
    sprite = new PIXI.Sprite(texture);
    sprite.anchor.x = .5;
    sprite.anchor.y = .5;
    sprite.position.x = this.position.x;
    sprite.position.y = this.position.y;
    sprite.width *= this.width || 1;
    sprite.height *= this.height || 1;
    return sprite;
  };

  default_update = function(dt) {
    this.xvel = this.xvel + this.xacel;
    this.yvel = this.yvel + this.yacel;
    this.position.x = this.position.x + this.xvel;
    this.position.y = this.position.y + this.yvel;
    this.xacel = (this.xacel + Math.random() - .5) * dt * this.acceleration;
    this.yacel = (this.yacel + Math.random() - .5) * dt * this.acceleration;
    this.xacel = this.xacel + (Math.pow(window.innerWidth / 2 - this.position.x, 3) * 0.00000001);
    this.yacel = this.yacel + (Math.pow(window.innerHeight / 2 - this.position.y, 3) * 0.00000001);
    return this;
  };

  new_ship = function(options) {
    if (options == null) {
      options = {};
    }
    return function(xpos, ypos) {
      return {
        type: "ship",
        render: options.render || default_render,
        update: options.update || default_update,
        position: {
          x: xpos || 0,
          y: ypos || 0
        },
        width: options.width,
        height: options.height,
        acceleration: options.acceleration || 0.1,
        xvel: 0,
        yvel: 0,
        xacel: 0,
        yacel: 0,
        texture: texture
      };
    };
  };

  module.exports = new_ship;

}).call(this);
