// Generated by CoffeeScript 1.6.1
(function() {
  var new_ship, texture;

  new_ship = require('../ship.js');

  texture = PIXI.Texture.fromImage("ship.png");

  module.exports = new_ship({
    health: 600,
    width: 2,
    height: 1.8
  });

}).call(this);
