// Generated by CoffeeScript 1.6.1
(function() {
  var render, texture, update;

  texture = PIXI.Texture.fromImage("ship.png");

  render = function() {
    var sprite;
    sprite = new PIXI.Sprite(texture);
    sprite.anchor.x = .5;
    sprite.anchor.y = .5;
    sprite.position.x = this.xpos;
    sprite.position.y = this.ypos;
    sprite.width *= 2;
    sprite.height *= 2;
    return sprite;
  };

  update = function(dt) {
    this.xvel = this.xvel + this.xacel;
    this.yvel = this.yvel + this.yacel;
    this.xpos = this.xpos + this.xvel;
    this.ypos = this.ypos + this.yvel;
    this.xacel = (this.xacel + Math.random() - .5) * dt * 0.1;
    this.yacel = (this.yacel + Math.random() - .5) * dt * 0.1;
    this.xacel = this.xacel + (Math.pow(200 - this.xpos, 3) * 0.00000001);
    this.yacel = this.yacel + (Math.pow(150 - this.ypos, 3) * 0.00000001);
    return this;
  };

  module.exports = function(xpos, ypos) {
    return {
      type: "ship",
      xpos: xpos,
      ypos: ypos,
      xvel: 0,
      yvel: 0,
      xacel: 0,
      yacel: 0,
      render: render,
      update: update
    };
  };

}).call(this);
