// Generated by CoffeeScript 1.6.1
(function() {
  var render, update;

  render = function() {
    var sprite;
    sprite = new PIXI.Sprite(this.texture);
    sprite.anchor.x = .5;
    sprite.anchor.x = .5;
    sprite.position.x = this.position.x;
    return sprite.position.y = this.position.y;
  };

  update = function(dt) {
    var curx, cury, destx, desty, diffx, diffy, total;
    destx = this.target.position.x;
    desty = this.target.position.y;
    curx = this.position.x;
    cury = this.position.y;
    diffx = destx - curx;
    diffy = desty - curx;
    return total = diffx + diffy;
  };

  module.exports = function(options) {
    return function(position) {
      return {
        type: 'projectile',
        acceleration: options.acceleration || 0,
        speed: options.speed,
        texture: options.texture,
        render: render,
        update: update,
        position: {
          x: position.x || 0,
          y: position.y || 0
        }
      };
    };
  };

}).call(this);
