// Generated by CoffeeScript 1.6.1
(function() {
  var closest, new_projectile_type, render, update;

  new_projectile_type = require('./projectile.js');

  closest = function(position, targets) {
    return targets[0];
  };

  render = void 0;

  update = function(dt, state) {
    var closest_ship, distance, new_projectile;
    this.cooldown = this.cooldown - dt;
    if (this.cooldown < 0) {
      this.cooldown = 0;
    }
    closest_ship = closest(this.position, state.targetables);
    distance = 0;
    if (this.cooldown === 0 && distance <= this.range) {
      new_projectile = this.fire_projectile({
        x: this.position.x,
        y: this.position.y
      }, closest_ship);
      this.cooldown = this.rate;
    }
    return [this].concat(new_projectile || []);
  };

  module.exports = function(options) {
    if (options == null) {
      options = {};
    }
    return function(position) {
      if (position == null) {
        position = {};
      }
      return {
        type: 'weapon',
        range: options.range || 50,
        rate: options.rate || 10,
        acceleration: options.acceleration || 0,
        update: update,
        cooldown: 0,
        position: {
          x: position.x || 0,
          y: position.y || 0
        },
        fire_projectile: new_projectile_type({
          texture: options.projectile.texture,
          speed: options.projectile.speed,
          acceleration: options.projectile.acceleration
        })
      };
    };
  };

}).call(this);
