// Generated by CoffeeScript 1.6.1
(function() {
  var new_projectile_type, render, update;

  new_projectile_type = require('./projectile.js');

  render = function() {};

  update = function(dt, state) {
    var closet_ship, new_projectile;
    if (this.cooldown < this.rate) {
      this.cooldown = this.cooldown + dt;
    }
    closet_ship = closest(ships);
    if (this.cooldown >= this.rate && distance <= this.range) {
      new_projectile = this.fire_projectile({
        position: {
          x: this.position.x,
          y: this.position.y
        }
      });
      this.cooldown = this.cooldown - this.rate;
    }
    return [this, new_projectile];
  };

  module.exports = function(options) {
    return function(position) {
      return {
        type: 'weapon',
        range: options.range || 50,
        rate: options.rate || 10,
        acceleration: options.acceleration || 0,
        render: render,
        position: {
          x: position.x || 0,
          y: position.y || 0
        },
        fire_projectile: new_projectile_type({
          texture: options.projectile.texture,
          speed: options.projectile.speed,
          acceleration: options.projectile.acceleration
        })
      };
    };
  };

}).call(this);
