// Generated by CoffeeScript 1.6.1
(function() {
  var lookup;

  lookup = function(object) {
    if (object.type === 'ship') {
      return require('./ship')(object);
    } else if (object.type === 'projectile') {
      return require('./projectile')(object);
    } else {
      return [];
    }
  };

  module.exports = lookup;

}).call(this);
