// Generated by CoffeeScript 1.6.1
(function() {

  module.exports = function(ship) {
    var sprite, texture;
    texture = PIXI.Texture.fromImage(ship.texture);
    sprite = new PIXI.Sprite(texture);
    sprite.anchor.x = .5;
    sprite.anchor.y = .5;
    sprite.position.x = ship.position.x;
    sprite.position.y = ship.position.y;
    sprite.width *= ship.width || 1;
    sprite.height *= ship.height || 1;
    return sprite;
  };

}).call(this);
