// Generated by CoffeeScript 1.6.1
(function() {
  var weapons;

  weapons = {
    laser: require('./laser'),
    cannon: require('./cannon'),
    sniper: require('./sniper'),
    sharknado: require('./sharknado')
  };

  module.exports = weapons;

}).call(this);
