// Generated by CoffeeScript 1.6.1
(function() {
  var newGroup;

  newGroup = function(id, max_persons) {
    return {
      id: id,
      persons: [],
      max_persons: max_persons,
      add: function(person) {
        return this.persons.push(person);
      },
      isFull: function() {
        return this.persons.length >= this.max_persons;
      }
    };
  };

  module.exports = {
    create: function(_arg) {
      var groups_spawned, lobby, max_persons, on_full, open_games, _ref;
      _ref = _arg != null ? _arg : {}, open_games = _ref.open_games, max_persons = _ref.max_persons, on_full = _ref.on_full;
      if (open_games == null) {
        open_games = 5;
      }
      if (max_persons == null) {
        max_persons = 4;
      }
      if (on_full == null) {
        on_full = function() {
          return true;
        };
      }
      lobby = {
        open_groups: {},
        current_id: 0,
        group: function(id) {
          var group,
            _this = this;
          group = this.open_groups[id];
          return {
            add: function(person) {
              group.add(person);
              if (group.isFull()) {
                on_full(group.persons);
                delete _this.open_groups[id];
                _this.spawnEmptyGroup();
              }
              return true;
            }
          };
        },
        spawnEmptyGroup: function() {
          return this.open_groups[this.current_id] = newGroup(this.current_id++, max_persons);
        }
      };
      groups_spawned = 0;
      while (groups_spawned++ < open_games) {
        lobby.spawnEmptyGroup();
      }
      return lobby;
    }
  };

}).call(this);
