// Generated by CoffeeScript 1.6.1
(function() {
  var app, find_space, gameUp, io, joinGame, port, server, update, url;

  app = require('express')();

  server = require('http').createServer(app);

  io = require('socket.io').listen(server);

  port = 8080;

  url = process.env.SUBDOMAIN != null ? "http://" + process.env.SUBDOMAIN + ".nodejitsu.com" : "http://localhost:" + port;

  server.listen(port);

  console.log("Express server listening on port " + port);

  console.log(url);

  gameUp = false;

  update = function(data, dt) {
    return {
      i: data.i + 1
    };
  };

  joinGame = function(socket) {
    var data, lastTime, loop_call;
    socket.join('game');
    if (!gameUp) {
      gameUp = true;
      data = {
        i: 0
      };
      lastTime = Date.now();
      return (loop_call = function() {
        var dt;
        dt = Date.now() - lastTime;
        data = update(data, dt);
        io.sockets["in"]('game').emit('update', data);
        return setTimeout(loop_call, 1000 / 120);
      })();
    }
  };

  find_space = function() {
    return "default room";
  };

  app.get('/game', function(req, res) {
    console.log('game started');
    return res.sendfile("" + __dirname + "/client/src/index.html");
  });

  io.sockets.on('connection', function(socket) {
    return joinGame(socket);
  });

}).call(this);
