// Generated by CoffeeScript 1.6.1
(function() {

  window.socket = socket;

  module.exports = {
    create: function(context, games) {
      var button, game, gameID, id, joinButtons, string, _i, _len, _results;
      string = "";
      for (id in games) {
        game = games[id];
        string += "<span>ID:</span> " + game.id + "\n<br />\n<span>Players: </span> " + game.players + "\n<br />\n<button class=\"join-button\"\n  data-game-id=\"" + game.id + "\">Join</button>";
      }
      joinButtons = document.getElementsByClassName('join-button');
      context.innerHTML = string;
      _results = [];
      for (_i = 0, _len = joinButtons.length; _i < _len; _i++) {
        button = joinButtons[_i];
        gameID = button.getAttribute('data-game-id');
        _results.push(button.onclick = function(x) {
          return socket.emit("join", this.getAttribute('data-game-id'));
        });
      }
      return _results;
    }
  };

}).call(this);
