// Generated by CoffeeScript 1.6.1
(function() {
  var new_ship, texture;

  new_ship = require('../ship.js');

  texture = PIXI.Texture.fromImage("/img/sharktopus.png");

  module.exports = new_ship({
    texture: texture,
    health: 5000,
    width: 1,
    height: 1
  });

}).call(this);
